In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

import scipy.stats as stat

In [5]:
data=pd.read_csv('Sales_data_zone_wise.csv')

# 1. The mean sales generated by each zone.

In [7]:
data.mean(axis=0)

Zone - A    1.540493e+06
Zone - B    1.755560e+06
Zone - C    1.772871e+06
Zone - D    1.842927e+06
dtype: float64

# 2. Total sales generated by all the zones for each month.

In [10]:
data.sum(axis=1)

0     7022544
1     7152303
2     6475939
3     8174449
4     5995328
5     7151387
6     7287108
7     7816299
8     6703395
9     7128210
10    7032783
11    6111084
12    5925424
13    7155515
14    5934156
15    6506659
16    7149383
17    7083490
18    6971953
19    7124599
20    7389597
21    7560001
22    6687919
23    7784747
24    6095918
25    6512360
26    6267918
27    7470920
28    6772277
dtype: int64

# 3. Check whether all the zones generate the same amount of sales.

Let,

Null hypothesis (H0) :- All the zones generate the same amount of sales.

Alternative hypothesis (Ha) :-  All the zones doesnot generate the same amount of sales.

set significance level, alpha as 0.05

if p value <0.05, we could reject the Null hypothesis and accept the Alternative hypothesis.

if p value >0.05, we could accept the null hypothesis and reject the Alternative hypothesis.

In [11]:
from scipy.stats import f_oneway

F, p = f_oneway(data['Zone - A'],data['Zone - B'],data['Zone - C'],data['Zone - D'])
print('F-statistic :',F)
print('p-value :',p)

F-statistic : 5.672056106843581
p-value : 0.0011827601694503335

In [15]:
if p<0.05:
    print('We reject the Null hypothesis; ie. all the zones generate the same amount of sales. We conclude that all the zones doesnot generate the same amount of sales.')
else:
    print('We accept the Null hypothesis; ie. all the zones doesnot generate the same amount of sales. We conclude that all the zones generate the same amount of sales.')

We reject the Null hypothesis; ie. all the zones generate the same amount of sales. We conclude that all the zones doesnot generate the same amount of sales.

In [16]:
data.sum(axis=0)

Month       Month - 1Month - 2Month - 3Month - 4Month - 5M...
Zone - A                                             44674301
Zone - B                                             50911228
Zone - C                                             51413260
Zone - D                                             53444876
dtype: object